version: "3.8"

services:
  backend:
    build: ./backend
    ports:
      - "8023:8023"
    volumes:
      - ./backend/uploads:/app/uploads
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - VITE_API_BASE=http://localhost:8023
    depends_on:
      - backend
    restart: unless-stopped
